language: python

nodoe_js:
  - node

cache: npm

python:
  - "3.8"

before_install:
  - python --version
  - python3 --version

install:
  - pip install pipenv

before_script:
  - cd graphery
  - npm install -g npm@latest

script:
  - npm run build && npm run test:unit
  - cd ../backend
  - pipenv install && pipenv install && pipenv run pytest
