language: python

nodoe_js:
  - node

cache:
  - npm
  - pip

python:
  - "3.8"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - sudo pip install pipenv
  - cd graphery
  - npm install -g npm@latest
  - npm install

script:
  - npm run build
  - cd ../backend && sudo pipenv install && sudo pipenv sync && sudo pipenv graph
  - cd ./bundle && sudo pipenv run pytest -vv -ra -s
  - cd ../server && sudo pipenv run pytest -vv -ra -s
