language: node_js

nodoe_js:
  - node

python:
  - "3.8.2"

install:
  - pip3 install pipenv
  - pipenv install

cache: npm

before_script:
  - cd graphery
  - npm install -g npm@latest
  - npm install codecov -g

script:
  - npm run build
  - rm -rf dist
  - npm run test:unit
  - cd ../backend && pipenv install && pipenv run pytest
