language: python

nodoe_js:
  - node

cache: npm

python:
  - "3.8"

install:
  - pip install pipenv
  - cd graphery
  - npm install -g npm@latest
  - npm install

script:
  - npm run build && npm run test:unit
  - cd ../backend
  - pipenv install && pipenv install && sudo pipenv run pytest
