site_name: Graphery Docs
theme:
  name: material
site_description: The documentation site for Graphery
markdown_extensions:
  - pymdownx.details
nav:
  - Home: "index.md"
  - "User Manual":
      - "Get Started": "./user-manual/get-started.md"
  - "Backend Doc":
      - "APIs": "./backend-docs/api-specification.md"
  - About: "about.md"
